version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm:
        patterns:
          - "*"
        applies-to: version-updates
      npm-security:
        patterns:
          - "*"
        applies-to: security-updates
    cooldown:
      default-days: 5
